<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.3" />
    <PackageReference Include="Microsoft.Agents.Builder.Testing" Version="1.8.77" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FabrCore.Services.Microsoft365Copilot\FabrCore.Services.Microsoft365Copilot.csproj" />
  </ItemGroup>

</Project>
