namespace FabrCore.Services.Memory.Models;

/// <summary>
/// Result of a synthetic imagining operation — contains the generated search queries
/// and the aggregated, deduplicated memory results from running those queries.
/// </summary>
public class SyntheticImaginingResult
{
    /// <summary>The search queries generated by the LLM from conversation analysis.</summary>
    public List<string> GeneratedQueries { get; set; } = [];

    /// <summary>
    /// Aggregated recall result: hot index (fetched once) plus deduplicated warm memories
    /// from all queries.
    /// </summary>
    public MemoryRecallResult AggregatedRecall { get; set; } = new();

    /// <summary>
    /// Deduplicated archive search results from all queries, ordered by distance (best match first).
    /// </summary>
    public List<MemorySearchResult> ArchiveResults { get; set; } = [];

    /// <summary>Total number of unique memories found across all queries.</summary>
    public int UniqueMemoryCount { get; set; }

    /// <summary>Whether the imagining operation completed successfully.</summary>
    public bool Success { get; set; }

    /// <summary>Error message if the operation failed, null on success.</summary>
    public string? ErrorMessage { get; set; }
}
